INSERT INTO pizza (nome, ingredientes, preco) VALUES('Alho e Óleo', 'Molho, mussarela, alho e óleo, orégano', 20) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Alicci', 'Molho, mussarela, alicci e orégano', 20) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Americana', 'molho, mussarela, bacon, milho, ovos e orégano', 21) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Atum', 'Molho, mussarela, atum e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Bacon', 'Molho, mussarela, bacon e orégano', 21) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Baiana', 'Molho, mussarela, calabresa, pimenta e orégano', 25) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Bolonhesa', 'Molho, mussarela, carne moída e orégano', 25) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Brasileira', 'Molho, mussarela, milho, ervilha e orégano', 20) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Brócolis', 'Molho, mussarela, brócolis, bacon, catupiry e orégano', 21) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Calabresa', 'Molho, mussarela, calabresa e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Calabresa com Catupiry', 'Molho, mussarela, calabresa, catupiry e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Calabresa com Cheddar', 'Molho, mussarela, calabresa, cheddar e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Calabresa Mineira', 'Molho, mussarela, calabresa, milho, bacon e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Camponesa', 'Molho, mussarela, frango, tomate picado, gorgonzola e manjericão', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Catupiry', 'Molho, mussarela, catupiry e orégano', 21) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Champignon', 'Molho, mussarela, champignon e orégano', 25) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Crocante', 'Molho, mussarela, presunto, bacon, milho, batata palha e orégano', 24) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Escarola', 'Molho, mussarela, escarola, alho, bacon e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Frango', 'Molho, mussarela, frango e orégano', 21) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Frango Caipira', 'Molho, mussarela, frango, catupiry, bacon, milho e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Frango com Catupiry', 'Molho, mussarela, frango, catupiry e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Frango com Cheddar', 'Molho, mussarela, frango, cheddar e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Gorgonzola', 'Molho, mussarela, tomate, gorgonzola e orégano', 26) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Grega', 'Molho, mussarela, lombo, cebola, palmito e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Havaiana', 'Molho, mussarela, lombo e abacaxi', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Humita', 'Molho, mussarela, presunto, milho e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo', 'Molho, mussarela, lombo e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo Califórnia', 'Molho, mussarela, lombo, califórnia e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo Canadense', 'Molho, mussarela, lombo, tomate, alicci, parmesão e orégano', 26) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo com Catupiry', 'Molho, mussarela, lombo, catupiry e orégano', 24) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo com Champignon', 'Molho, mussarela, lombo, champignon e orégano', 24) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo com Cheddar', 'Molho, mussarela, lombo, cheddar e orégano', 24) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Lombo Especial', 'Molho, mussarela, lombo, champignon, catupiry e orégano', 27) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Maguerita', 'Molho, mussarela, tomate e manjericão', 28) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Maiale', 'Molho, mussarela, lombo, calabresa, bacon e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Marinara', 'Molho, mussarela, atum, tomate picado, provolone e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Mexicana', 'Molho, mussarela, calabresa, cebola, pimenta e orégano', 22) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Milho Verde', 'Molho, mussarela, milho verde e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Mussarela', 'Molho, mussarela e orégano', 27) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Napolitana', 'Molho, mussarela, tomate, parmesão e orégano', 20) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Palmito', 'Molho, mussarela, palmito e orégano', 21) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Palmito Especial', 'Molho, mussarela, palmito, milho, bacon e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Parmegiana', 'Mussarela, molho ao sugo, parmesão e orégano', 25) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Paulista', 'Molho, mussarela, palmito, ervilha e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Peruana', 'Massa, molho, mussarela, atum, cebola, ervilha e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Portuguesa', 'Molho, mussarela, presunto, cebola, ovos, azeitona e orégano', 26) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Provolone', 'Molho, mussarela, provolone e orégano', 25) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('QDelícia', 'Molho, mussarela, bolonhesa, cebola, batata palha e orégano', 27) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Quatro Queijos', 'Molho, mussarela, provolone, parmesão, catupiry e orégano', 29) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Romana', 'Molho, mussarela, presunto e orégano', 23) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Siciliana', 'Molho, mussarela, champignon, bacon, pimentão, azeitona e orégano', 20) ;
INSERT INTO pizza (nome, ingredientes, preco) VALUES('Vegetariana', 'Molho, mussarela, escarola, tomate, milho, ervilha e orégano', 24) ;


INSERT INTO forma_de_pagamento (nome) VALUES ('Dinheiro') ;
INSERT INTO forma_de_pagamento (nome) VALUES ('Dinheiro com Troco') ;
INSERT INTO forma_de_pagamento (nome) VALUES ('Cartao de Credito') ;
INSERT INTO forma_de_pagamento (nome) VALUES ('Cartao de Debito') ;

INSERT INTO cliente (login, senha, nome, telefone, endereco) values ('dev', 'dev', 'nome', 'telefone', 'endereco');